### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown color

### ISSUE THREAD

**Issue by rmasarovic** [tarek360/RichPath#20]
Hi when i used this in vector 

<path
        android:name="friend_cross_vertical"
        android:pathData="M23,11h-6"
        android:strokeLineCap="round"
        android:strokeColor="#000"
        android:fillType="evenOdd"
        android:fillColor="#00000000"
        android:strokeWidth="2"
        android:trimPathEnd="0"
        android:strokeLineJoin="round"/>

problem is in fillColor value. I have error  

Caused by: java.lang.IllegalArgumentException: Unknown color
                      at android.graphics.Color.parseColor(Color.java:154)
                      at com.richpath.util.XmlParser.getAttributeColor(XmlParser.java:134)
                      at com.richpath.RichPath.inflate(RichPath.java:413)
                      at com.richpath.util.XmlParser.parsePathElement(XmlParser.java:89)
                      at com.richpath.util.XmlParser.parseVector(XmlParser.java:56)
                      at com.richpath.RichPathView.setVectorDrawable(RichPathView.java:83)
                      at com.richpath.RichPathView.setupAttributes(RichPathView.java:66)
                      at com.richpath.RichPathView.<init>(RichPathView.java:44)
E/AndroidRuntime:     at com.richpath.RichPathView.<init>(RichPathView.java:38)

**Comment by tarek360** [comment]
hi, please put your XML code and your Java code to know how you use RichPath
maybe setting the color from the resources is the problem, but lets me see the code first.

**Comment by rmasarovic** [comment]
i push my test project to github here https://github.com/rmasarovic/RichPathAnimationTest  when you run it app will crash.  when you change in ic_add_to_friends.xml in tag friend_head android:fillColor="#00000000" to android:fillColor="#FFFFFFFF" it will be work

**Comment by tarek360** [comment]
@rmasarovic 
fixed, check this snapshot
```gradle
implementation 'com.github.tarek360.RichPath:animator:fix~color-parsing-SNAPSHOT'
```

**Comment by rmasarovic** [comment]
yep snapshot fix this
