### ISSUE TITLE
Binary XML file line #0: Error inflating class com.richpath.RichPathView

### ISSUE THREAD

**Issue by gfmx2048** [tarek360/RichPath#24]
Hello,
I have already use the library at other sample projects and works perfect.

i created a new project:
        minSdkVersion 21
        targetSdkVersion 26

```
  <com.richpath.RichPathView
        android:id="@+id/rpv_loader"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="170dp"
        app:vector="@drawable/ic_accept_48" />
```

xml preview works fine but when i run the app it crashes with:

```
**FATAL EXCEPTION:  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myalgosapp.www.myalgos/com.myalgosapp.www.myalgos.activities.dashboard.ActivityConnect}: android.view.InflateException: Binary XML file line #0: Error inflating class com.richpath.RichPathView
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.richpath.RichPathView
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                              at com.myalgosapp.www.myalgos.activities.dashboard.ActivityConnect.onCreate(ActivityConnect.java:17)
                                                                              at android.app.Activity.performCreate(Activity.java:5990)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                           Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                              at com.myalgosapp.www.myalgos.activities.dashboard.ActivityConnect.onCreate(ActivityConnect.java:17) 
                                                                              at android.app.Activity.performCreate(Activity.java:5990) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                           Caused by: java.lang.IllegalArgumentException: Unknown color
                                                                              at android.graphics.Color.parseColor(Color.java:216)
                                                                              at com.richpath.util.XmlParser.getAttributeColor(XmlParser.java:134)
                                                                              at com.richpath.RichPath.inflate(RichPath.java:413)
                                                                              at com.richpath.util.XmlParser.parsePathElement(XmlParser.java:89)
                                                                              at com.richpath.util.XmlParser.parseVector(XmlParser.java:56)
                                                                              at com.richpath.RichPathView.setVectorDrawable(RichPathView.java:83)
                                                                              at com.richpath.RichPathView.setupAttributes(RichPathView.java:66)
                                                                              at com.richpath.RichPathView.<init>(RichPathView.java:44)
                                                                              at com.richpath.RichPathView.<init>(RichPathView.java:38)
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                              at com.myalgosapp.www.myalgos.activities.dashboard.ActivityConnect.onCreate(ActivityConnect.java:17) 
                                                                              at android.app.Activity.performCreate(Activity.java:5990) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)** 

```

Thank you for your time!

**Comment by gfmx2048** [comment]
**the problem:**
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportHeight="48.0"
    android:viewportWidth="48.0">
    <path
        android:name="circle"
        android:fillColor="@color/colorWhite"
        android:pathData="M47,24c0,12.69 -10.31,23 -23,23C11.3,47 1,36.69 1,24C1,11.3 11.3,1 24,1C36.69,1 47,11.31 47,24z"
        android:strokeColor="@color/colorGrayDarkText"
        android:strokeWidth="0.92" />
    <path
        android:name="tick"
        **android:fillColor="#00000000"**
        android:pathData="M14.32,24l9.09,10.65l9.07,-24.14"
        android:strokeColor="@color/colorGrayDarkText"
        android:strokeWidth="1.84" />
</vector>
```
 
**the solution:**
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportHeight="48.0"
    android:viewportWidth="48.0">
    <path
        android:name="circle"
        android:fillColor="@color/colorWhite"
        android:pathData="M47,24c0,12.69 -10.31,23 -23,23C11.3,47 1,36.69 1,24C1,11.3 11.3,1 24,1C36.69,1 47,11.31 47,24z"
        android:strokeColor="@color/colorGrayDarkText"
        android:strokeWidth="0.92" />
    <path
        android:name="tick"
        **android:fillColor="#FFFFFF"**
        android:pathData="M14.32,24l9.09,10.65l9.07,-24.14"
        android:strokeColor="@color/colorGrayDarkText"
        android:strokeWidth="1.84" />
</vector>
```
