### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by farhanlatheef** [tarek360/RichPath#49]
When try to animate below code
```
String scanPath = getString(R.string.scan_path1);
        String qrPath = getString(R.string.qr_path1);
        final RichPath richPath = qrAnim.findFirstRichPath();
        RichPathAnimator
                .animate(richPath)
                .pathData(scanPath)
                .duration(600)
                .thenAnimate(richPath)
                .pathData(qrPath)
                .duration(600)
                .start();
```

and two concerned strings

```
 <string name="qr_path1">M 0 224 L 192 224 L 192 32 L 0 32 L 0 224 Z M 64 96 L 128 96 L 128 160 L 64 160 L 64 96 Z M 256 32 L 256 224 L 448 224 L 448 32 L 256 32 Z M 384 160 L 320 160 L 320 96 L 384 96 L 384 160 Z M 0 480 L 192 480 L 192 288 L 0 288 L 0 480 Z M 64 352 L 128 352 L 128 416 L 64 416 L 64 352 Z M 416 288 L 448 288 L 448 416 L 352 416 L 352 384 L 320 384 L 320 480 L 256 480 L 256 288 L 352 288 L 352 320 L 416 320 L 416 288 Z M 416 448 L 448 448 L 448 480 L 416 480 L 416 448 Z M 352 448 L 384 448 L 384 480 L 352 480 L 352 448 Z</string>
    <string name="scan_path1">M 3 5 L 3 9 L 5 9 L 5 5 L 9 5 L 9 3 L 5 3 C 3.9 3 3 3.9 3 5 Z M 5 15 L 3 15 L 3 19 C 3 20.1 3.9 21 5 21 L 9 21 L 9 19 L 5 19 L 5 15 Z M 19 19 L 15 19 L 15 21 L 19 21 C 20.1 21 21 20.1 21 19 L 21 15 L 19 15 L 19 19 Z M 19 3 L 15 3 L 15 5 L 19 5 L 19 9 L 21 9 L 21 5 C 21 3.9 20.1 3 19 3 Z</string>
```

Got below error

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.richpathanimator.PathEvaluator.evaluate(PathEvaluator.java:26)
        at com.richpathanimator.PathEvaluator.evaluate(PathEvaluator.java:12)
        at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
        at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1531)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:668)
        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:631)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1060)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1079)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1072)
        at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1142)
        at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1227)
```

**Comment by sethepeterson** [comment]
I am getting the same exception except mine says "length=1; index=1".

Did you end up figuring out a solution?

**Comment by farhanlatheef** [comment]
I got the error because i put two random paths together and hoped it works. actually you have to create the shape shifting using this tool. https://shapeshifter.design/
