### ISSUE TITLE
crash on load :did not set the measured dimension by calling setMeasuredDimension()

### ISSUE THREAD

**Issue by techker** [tarek360/RichPath#66]
Hello how do i fix the error:

4: com.richpath.RichPathView#onMeasure() did not set the measured dimension by calling setMeasuredDimension()

 val richPath: RichPath? = imageViewCalibrate.findRichPathByName("1")
        RichPathAnimator.animate(richPath)
                .fillColor(Color.WHITE)
                .start()

java.lang.IllegalStateException: View with id 2131231004: com.richpath.RichPathView#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
        at android.view.View.measure(View.java:25461)
        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6884)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:739)
        at android.view.View.measure(View.java:25448)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3361)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2203)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2460)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1934)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8127)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by tarek360** [comment]
Please provide your vector drawable file and how to reproduce it?
