### ISSUE TITLE
Non-SDK usage causing RichPathView.setVectorDrawable to throw an exception when targeting API Level 31

### ISSUE THREAD

**Issue by tomdug** [tarek360/RichPath#76]
With the release of Android 12, a bunch of non-SDK interfaces were removed (see [this](https://developer.android.com/about/versions/12/non-sdk-12#new-blocked)).

And this library uses reflection to call this non-SDK method with is now blocked in Android 12:
`Landroid/util/PathParser;->createPathFromPathData(Ljava/lang/String;)Landroid/graphics/Path;`

Trying to call `RichPathView.setVectorDrawable` thus causes this exception to be thrown:
```
W/ Accessing hidden method Landroid/util/PathParser;->createPathFromPathData(Ljava/lang/String;)Landroid/graphics/Path; (max-target-r, reflection, denied)
W/System.err: java.lang.NoSuchMethodException: android.util.PathParser.createPathFromPathData [class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getDeclaredMethod(Class.java:2081)
        at com.richpath.pathparser.PathParserCompatApi21.getCreatePathFromPathDataMethod(PathParserCompatApi21.java:37)
        at com.richpath.pathparser.PathParserCompatApi21.createPathFromPathData(PathParserCompatApi21.java:21)
        at com.richpath.pathparser.PathParser.createPathFromPathData(PathParser.java:18)
        at com.richpath.RichPath.<init>(RichPath.java:71)
        at com.richpath.util.XmlParser.parsePathElement(XmlParser.java:87)
        at com.richpath.util.XmlParser.parseVector(XmlParser.java:55)
        at com.richpath.RichPathView.setVectorDrawable(RichPathView.java:84)
```

**Comment by tarek360** [comment]
Thank you for reporting this issue, I'd check that this week.
